import type { Fixture } from './constants'

// MLS team logo URLs from official MLS CDN
export const MLS_LOGOS: Record<string, string> = {
  'Atlanta United': 'https://images.mlssoccer.com/image/upload/assets/logos/ATL.svg',
  'Austin FC': 'https://images.mlssoccer.com/image/upload/assets/logos/ATX.svg',
  'Charlotte FC': 'https://images.mlssoccer.com/image/upload/v1610563331/assets/logos/CLT.svg',
  'Chicago Fire': 'https://images.mlssoccer.com/image/upload/v1633104740/assets/logos/CHI_Logo-2021.svg',
  'FC Cincinnati': 'https://images.mlssoccer.com/image/upload/assets/logos/CIN.svg',
  'Colorado Rapids': 'https://images.mlssoccer.com/image/upload/assets/logos/COL.svg',
  'Columbus Crew': 'https://images.mlssoccer.com/image/upload/assets/logos/CLB-Logo-2021-Reversed.svg',
  'FC Dallas': 'https://images.mlssoccer.com/image/upload/assets/logos/DAL.svg',
  'D.C. United': 'https://images.mlssoccer.com/image/upload/assets/logos/DC.svg',
  'Houston Dynamo': 'https://images.mlssoccer.com/image/upload/v1610562955/assets/logos/HOU.svg',
  'Sporting KC': 'https://images.mlssoccer.com/image/upload/assets/logos/SKC.svg',
  'LA Galaxy': 'https://images.mlssoccer.com/image/upload/assets/logos/LA.svg',
  'LAFC': 'https://images.mlssoccer.com/image/upload/assets/logos/LAFC.svg',
  'Inter Miami': 'https://images.mlssoccer.com/image/upload/assets/logos/MIA.svg',
  'Minnesota United': 'https://images.mlssoccer.com/image/upload/assets/logos/MIN.svg',
  'CF Montréal': 'https://images.mlssoccer.com/image/upload/v1668018023/assets/mtl/logos/Montreal-Club-colored_MLS_Crest-480x480.svg',
  'Nashville SC': 'https://images.mlssoccer.com/image/upload/assets/logos/NSH.svg',
  'New England Revolution': 'https://images.mlssoccer.com/image/upload/v1766020750/assets/NE_Logo_PRI_FC_RGB_480x480_fdx2us.png',
  'New York Red Bulls': 'https://images.mlssoccer.com/image/upload/assets/logos/RBNY.svg',
  'New York City FC': 'https://images.mlssoccer.com/image/upload/v1747756306/assets/logos/mls-clubs/Club_Logo-New_York_City_xu6vax.png',
  'Orlando City': 'https://images.mlssoccer.com/image/upload/assets/logos/ORL.svg',
  'Philadelphia Union': 'https://images.mlssoccer.com/image/upload/assets/logos/PHI.svg',
  'Portland Timbers': 'https://images.mlssoccer.com/image/upload/v1626094359/assets/logos/POR-Logo_wviuqh.svg',
  'Real Salt Lake': 'https://images.mlssoccer.com/image/upload/v1625175975/assets/logos/RSL-Logo_l7qgl3',
  'San Diego FC': 'https://images.mlssoccer.com/image/upload/v1736288310/assets/sd_logo_pri_fc_rgb_480x480__1__720_1_ipr7gj.png',
  'San Jose Earthquakes': 'https://images.mlssoccer.com/image/upload/assets/logos/SJ.svg',
  'Seattle Sounders': 'https://images.mlssoccer.com/image/upload/v1702319240/assets/sea/logos/SEA2023-Full_Color-480x480_fk6mpu.png',
  'St. Louis City': 'https://images.mlssoccer.com/image/upload/v1610563329/assets/logos/STL.svg',
  'Toronto FC': 'https://images.mlssoccer.com/image/upload/assets/logos/TOR.svg',
  'Vancouver Whitecaps': 'https://images.mlssoccer.com/image/upload/assets/logos/VAN.svg',
}

// Mock schedule data for local development
export const MOCK_FIXTURES: Fixture[] = [
  {
    id: 1,
    date: '2026-03-01',
    time: '19:30',
    opponent: 'LA Galaxy',
    opponentLogo: MLS_LOGOS['LA Galaxy'],
    isHome: true,
    venue: 'Providence Park',
    competition: 'MLS',
  },
  {
    id: 2,
    date: '2026-03-08',
    time: '17:00',
    opponent: 'Seattle Sounders',
    opponentLogo: MLS_LOGOS['Seattle Sounders'],
    isHome: false,
    venue: 'Lumen Field',
    competition: 'MLS',
  },
  {
    id: 3,
    date: '2026-03-15',
    time: '19:30',
    opponent: 'LAFC',
    opponentLogo: MLS_LOGOS['LAFC'],
    isHome: true,
    venue: 'Providence Park',
    competition: 'MLS',
  },
  {
    id: 4,
    date: '2026-03-22',
    time: '18:00',
    opponent: 'San Jose Earthquakes',
    opponentLogo: MLS_LOGOS['San Jose Earthquakes'],
    isHome: false,
    venue: 'PayPal Park',
    competition: 'MLS',
  },
  {
    id: 5,
    date: '2026-03-29',
    time: '19:30',
    opponent: 'Real Salt Lake',
    opponentLogo: MLS_LOGOS['Real Salt Lake'],
    isHome: true,
    venue: 'Providence Park',
    competition: 'MLS',
  },
]
